language: python
python:
    - "3.6"

#to install dependancies
install:
    - pip install -r requirements.txt
    - cat requirements.txt

#to run tests
script:
    - nosetests tests

#to run coverage tests
after_success:
    - cd tests 
    - coverage run --source='.' test_user.py test_meals.py test_menu.py test_orders.py
    - coveralls
cache:
    -pip
