language: python
python:
    - "3.6"

#to install dependancies
install:
    - export FLASK_APP="run.py"
    
    - pip install -r requirements.txt

#to run tests
script:
    - nosetests tests

#to run coverage tests
after_success: 
    - coveralls

cache:
    -pip
