language: python
python:
    - "3.6"

#to install dependancies
install:
    - pip install -r requirements.txt
    - cat requirements.txt

#to run tests
script:
    - nosetests tests

#to run coverage tests
after_success: 
    - coverage run --source='.' nosetests tests
    - coveralls
cache:
    - pip
