language: python
python:
    - "3.6"

#to install dependancies
install:
    - pip install -r requirements.txt

#to run tests
script:
    - nosetests tests

#to run coverage tests
after_success: 
    - coverage run --source='.' tests/test_user.py, tests/test_meals.py, tests/test_menu.py, tests/test_orders.py
    - coveralls

cache:
    -pip
